src/HRMSProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from .docs.generators import OpenAPISchemaGenerator
from .docs.swagger_intro import DESCRIPTION

from .db_setup import DBCreation, CentralCompanyCreationAPIView, CreateCompany

app_urls = [
    path("admin/", admin.site.urls),
    path('api/roles/', include("roles.urls")),
    path("api/user/", include("HRMSApp.urls")),
    path("api/company/", include("company_profile.urls")),
    path("api/directory/", include("directory.urls")),
    path("api/choices/", include("choices.urls")),
    path("api/reports/", include("reports.urls")),
    path("api/pss_calendar/", include("pss_calendar.urls")),
    path("api/leave/", include("leave.urls")),
    path("api/attendance/", include("attendance.urls")),
    path("api/performance_management/", include("performance_management.urls")),
    path("api/investment_declaration/", include("investment_declaration.urls")),
    path("api/payroll/", include("payroll.api_urls")),
    path("payroll/", include("payroll.urls")),    
    path('support/', include(("support.urls", "support"), namespace='support')),
    path('billing/', include(("billing.urls", "billing"), namespace='billing')),
    path('central/db_setup/', CreateCompany.as_view()),
    path('central/company_setup/', CentralCompanyCreationAPIView.as_view()),
    path('api/aiml/', include("aiml_app.urls")),
    path('api/alerts/', include("alerts.urls")),
    path('api/onboarding/', include("onboarding.urls")),
]


schema_view = get_schema_view(
    openapi.Info(
        title="HRMS Software API",
        default_version="v1",
        description=DESCRIPTION,
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@pss.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    generator_class=OpenAPISchemaGenerator,
    patterns=app_urls,
)

external_urls = [
    # re_path(
    #     r"^swagger(?P<format>\.json|\.yaml)$",
    #     schema_view.without_ui(cache_timeout=0),
    #     name="schema-json",
    # ),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # re_path(
    #     r"^docs/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    # ),
    # OpenAPI schema
    # path(
    #     "docs/",
    #     schema_view.with_ui("redoc", cache_timeout=0),
    #     name="openapi-schema",
    # ),
]

urlpatterns = external_urls + app_urls
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/support/urls.py
from django.urls import path

from .views import TicketApiView, CentralTicketUpdateAPIView

urlpatterns = [
    path('ticketapi/', TicketApiView.as_view(), name='ticketapi'),
    path('ticketapi/listing-tickets/', TicketApiView.as_view(), name='listing_ticketapi'),
    path('ticketapi/create/', TicketApiView.as_view(), name='ticketapi_create'),
    path('ticketapi/auto/update/', CentralTicketUpdateAPIView.as_view(), name='ticketapi_auto_update'),
]

support/urls.py
from django.urls import path

from .views import TicketApiView, CentralTicketUpdateAPIView

urlpatterns = [
    path('ticketapi/', TicketApiView.as_view(), name='ticketapi'),
    path('ticketapi/listing-tickets/', TicketApiView.as_view(), name='listing_ticketapi'),
    path('ticketapi/create/', TicketApiView.as_view(), name='ticketapi_create'),
    path('ticketapi/auto/update/', CentralTicketUpdateAPIView.as_view(), name='ticketapi_auto_update'),
]

src/support/models.py
import uuid
import random
import string

from django.db import models


def random_string_generator(size=20, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

class Tickect(models.Model):
    class TicketStatus(models.TextChoices):
        PENDING = 'pen', 'Pending'
        RESOLVED = 'res', 'Resolved'
        INVALID = 'inv', 'Invalid'
        PROCESSING = 'pro', 'Processing'
    
    class TicketCategory(models.TextChoices):
        BILLINGISSUE = 'billingissue', 'BillingIssue'
        ACCESSISSUE = 'accessissue', 'AccessIssue'
        PAYROLLISSUE = 'payrollissue', 'PayrollIssue'
    
    ticket_id = models.CharField(max_length=128, null=True, blank=True)
    title = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    category = models.CharField(max_length=28, choices=TicketCategory.choices, default='')
    raised_by = models.JSONField(default=dict, null=True, blank=True)
    resolved_by = models.JSONField(default=dict, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=16, choices=TicketStatus.choices, default=TicketStatus.PENDING)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.ticket_id} {self.status}'
    
    def generate_ticket_id(self):
        return random_string_generator(chars=string.ascii_uppercase + string.digits)

    def save(self, *args, **kwargs):
        ticket_id = self.generate_ticket_id()
        if self.__class__.objects.filter(ticket_id=ticket_id).exists():
            ticket_id = self.generate_ticket_id()
        self.ticket_id = ticket_id
        return super().save(*args, **kwargs)

support/models.py
import uuid
import random
import string

from django.db import models


def random_string_generator(size=20, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

class Tickect(models.Model):
    class TicketStatus(models.TextChoices):
        PENDING = 'pen', 'Pending'
        RESOLVED = 'res', 'Resolved'
        INVALID = 'inv', 'Invalid'
        PROCESSING = 'pro', 'Processing'
    
    class TicketCategory(models.TextChoices):
        BILLINGISSUE = 'billingissue', 'BillingIssue'
        ACCESSISSUE = 'accessissue', 'AccessIssue'
        PAYROLLISSUE = 'payrollissue', 'PayrollIssue'
    
    ticket_id = models.CharField(max_length=128, null=True, blank=True)
    title = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    category = models.CharField(max_length=28, choices=TicketCategory.choices, default='')
    raised_by = models.JSONField(default=dict, null=True, blank=True)
    resolved_by = models.JSONField(default=dict, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=16, choices=TicketStatus.choices, default=TicketStatus.PENDING)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.ticket_id} {self.status}'
    
    def generate_ticket_id(self):
        return random_string_generator(chars=string.ascii_uppercase + string.digits)

    def save(self, *args, **kwargs):
        ticket_id = self.generate_ticket_id()
        if self.__class__.objects.filter(ticket_id=ticket_id).exists():
            ticket_id = self.generate_ticket_id()
        self.ticket_id = ticket_id
        return super().save(*args, **kwargs)

src/support/views.py
import requests

import django
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model, authenticate, logout, login
from django.shortcuts import redirect
from django.db.models import Q, Value, F, CharField
from django.db.models.functions import Concat
from django.http import HttpResponse, JsonResponse
from django.contrib.postgres.aggregates import ArrayAgg
from django.utils.text import slugify
from django.db import transaction

from rest_framework import status, permissions, authentication
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer

from .models import Tickect
from core.central_permissions import IsCentralOrAuthenticated

class TicketApiView(APIView):
    # permission_classes = [permissions.IsAuthenticated]
    permission_classes = (permissions.AllowAny, )
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]

    def get(self, request):
        print(request.headers)
        data = Tickect.objects.all().values()
        # return Response({ "request": request, "data":qs},template_name='ticket.html')
        # return Response({ 
        #                  "request": request,
        #                  "data":qs,
        #                  'activeFor':'create_ticket'
        #             },template_name='create_ticket.html'
        #         )
        
        if "ticketapi/create/" in request.path:
            templ = "create_ticket.html"
            activeFor = "create_ticket"
        elif "listing-tickets" in request.path:
            templ = "listing_tickets.html"
            activeFor = "listing_tickets"
        else:
            templ = "create_ticket.html"   
            activeFor = "create_ticket" 
            
        return Response(
            {
                "data": data,
                'activeFor':activeFor
            },
            template_name=templ
        )
    
    def post(self, request):
        data = request.data
        user = request.user
        title = data['title']
        ticket_obj = Tickect.objects.create(
            title=title, description=data.get('description'),
            raised_by={'id': user.id, 'name': user.employee_details.first().name},
            category=data['category']
        )
        url = 'http://54.210.248.129/support/tickets/'
        resp = requests.post(url, json={
            'ticket_id': ticket_obj.ticket_id,
            'title': ticket_obj.title,
            'description': ticket_obj.description,
            'organization': request.user.employee_details.first().company.company_name,
            'raised_by': ticket_obj.raised_by,
            'status': ticket_obj.status,
            'category': ticket_obj.category
        })
        
        # return redirect('support:ticketapi')
        return Response({
            "response": 'success',
            "msg":"",
            "title":"Success",
            "type":"success",
            "status":status.HTTP_200_OK
        })
    
    def put(self, request):
        data = request.data
        ticket_pk = data.get('id')
        obj = get_object_or_404(Tickect, id=ticket_pk)
        obj.update(**data)
        obj.save()
        return Response("Updated Successfully")

class CentralTicketUpdateAPIView(APIView):
    permission_classes = (permissions.AllowAny, )
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    
    def put(self, request):
        data = request.data
        ticket_id = data['ticket_id']
        ticket_obj = get_object_or_404(Tickect, ticket_id=ticket_id)
        ticket_obj.comments = data.get('comments')
        ticket_obj.status = data.get('status')
        ticket_obj.resolved_by = data.get('resolved_by')
        ticket_obj.save()
        # return Response("Updated Successfully")
        return Response({
            "response": 'success',
            "msg":"",
            "title":"Success",
            "type":"success",
            "status":status.HTTP_200_OK
        })

support/views.py
import requests

import django
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model, authenticate, logout, login
from django.shortcuts import redirect
from django.db.models import Q, Value, F, CharField
from django.db.models.functions import Concat
from django.http import HttpResponse, JsonResponse
from django.contrib.postgres.aggregates import ArrayAgg
from django.utils.text import slugify
from django.db import transaction

from rest_framework import status, permissions, authentication
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer

from .models import Tickect
from core.central_permissions import IsCentralOrAuthenticated

class TicketApiView(APIView):
    # permission_classes = [permissions.IsAuthenticated]
    permission_classes = (permissions.AllowAny, )
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]

    def get(self, request):
        print(request.headers)
        data = Tickect.objects.all().values()
        # return Response({ "request": request, "data":qs},template_name='ticket.html')
        # return Response({ 
        #                  "request": request,
        #                  "data":qs,
        #                  'activeFor':'create_ticket'
        #             },template_name='create_ticket.html'
        #         )
        
        if "ticketapi/create/" in request.path:
            templ = "create_ticket.html"
            activeFor = "create_ticket"
        elif "listing-tickets" in request.path:
            templ = "listing_tickets.html"
            activeFor = "listing_tickets"
        else:
            templ = "create_ticket.html"   
            activeFor = "create_ticket" 
            
        return Response(
            {
                "data": data,
                'activeFor':activeFor
            },
            template_name=templ
        )
    
    def post(self, request):
        data = request.data
        user = request.user
        title = data['title']
        ticket_obj = Tickect.objects.create(
            title=title, description=data.get('description'),
            raised_by={'id': user.id, 'name': user.employee_details.first().name},
            category=data['category']
        )
        url = 'http://54.210.248.129/support/tickets/'
        resp = requests.post(url, json={
            'ticket_id': ticket_obj.ticket_id,
            'title': ticket_obj.title,
            'description': ticket_obj.description,
            'organization': request.user.employee_details.first().company.company_name,
            'raised_by': ticket_obj.raised_by,
            'status': ticket_obj.status,
            'category': ticket_obj.category
        })
        
        # return redirect('support:ticketapi')
        return Response({
            "response": 'success',
            "msg":"",
            "title":"Success",
            "type":"success",
            "status":status.HTTP_200_OK
        })
    
    def put(self, request):
        data = request.data
        ticket_pk = data.get('id')
        obj = get_object_or_404(Tickect, id=ticket_pk)
        obj.update(**data)
        obj.save()
        return Response("Updated Successfully")

class CentralTicketUpdateAPIView(APIView):
    permission_classes = (permissions.AllowAny, )
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    
    def put(self, request):
        data = request.data
        ticket_id = data['ticket_id']
        ticket_obj = get_object_or_404(Tickect, ticket_id=ticket_id)
        ticket_obj.comments = data.get('comments')
        ticket_obj.status = data.get('status')
        ticket_obj.resolved_by = data.get('resolved_by')
        ticket_obj.save()
        # return Response("Updated Successfully")
        return Response({
            "response": 'success',
            "msg":"",
            "title":"Success",
            "type":"success",
            "status":status.HTTP_200_OK
        })

support/templates/listing_tickets.html
{% extends 'payroll/base/base.html' %}
{% load static %}

{% block main_content%}
    
    <div class="container-fluid">
           <div class="block-header">
             <div class="pb-3">
                 <div class="header">
                     <ul class="nav nav-tabs2 text-center">
                         <li class="nav-item px-0" style="width: 20%; margin-left: 20px; margin-right: 20px;"><span class="my_circleBtn">1</span><a class="nav-link  pt-3 pb-3  pl-4 {% if activeFor == 'listing_tickets' %}{{'active show'}}{% else %}{{''}}{% endif %}" data-toggle="tab" id="ESI_listtypes" href="#l_ESITypes" onclick="location.href='/qxbox{% url 'support:listing_ticketapi' %}'">Ticket Listing</a></li>
                         <li class="nav-item px-0" style="width: 20%; margin-left: 20px; margin-right: 20px;"><span class="my_circleBtn">2</span><a class="nav-link pt-3 pb-3 pl-4 {% if activeFor == 'create_ticket' %}{{'active show'}}{% else %}{{''}}{% endif %}" data-toggle="tab" id="EPF_listtypes" href="#l_EPF_Types" onclick="location.href='/qxbox{% url 'support:ticketapi_create' %}'">Create Ticket</a></li>
                     </ul>
                     <!-- <li class="nav-item"><a class="nav-link active show" data-toggle="tab" id="departlisttypes" href="#l_departtypes">Departments</a></li> -->
                 </div>
             </div>
 
             <div class="row clearfix pt-4">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="row pb-5 row">
                            <div class="col-md-4 col-sm-12">
                                <h1 class="ico_head" style="
                                font-size: large;
                            "><i class="icon-grid"></i> Ticket Listing </h1>
                            </div>
                            {% comment %} <div class="col-md-8 col-sm-12 text-right">
                                <button type="button" class="btn addBtn mr-2" data-toggle="modal" data-target="#addDepartmentModal">Add Department</button>                        
                                <a href="javascript:void(0);" class="full-screen"><i class="icon-frame"></i></a>
                            </div> {% endcomment %}
                            <div class="col-md-6 col-sm-12 text-right hidden-xs"></div>
                        </div>
                     
                        <div class="body shadow-lg">
                            <div class="tab-content mt-0">
                                <div class="tab-pane show active" id="l_departtypes">
                                    <div class="table-responsive">
                                        <table class="table table-hover table-custom spacing5 mb-0" id="deptTable">
                                            <thead>
                                                <tr>
                                                    <th>S No.</th> 
                                                    <th>Ticket ID</th>
                                                    <th>Title</th>
                                                    <th>Category</th>
                                                    <th>Description</th>
                                                    <th>Organization Name</th>
                                                    <th>Comments</th>
                                                    <th>Rised By</th>
                                                    <th>Resolved By</th>
                                                    <th>Created At</th>
                                                    <th>Ticket Status</th>
                                                </tr>
                                            </thead>
                                            <tbody>

                                                {% for listing in data %}

                                                    <tr>
                                                        <td>{{ forloop.counter }}</td>                                                    
                                                        <td>{{ listing.ticket_id }}</td>                                                    
                                                        <td>{{ listing.title | title }}</td>  

                                                        <td>
                                                            {% if listing.category and listing.category == 'billingissue' %}
                                                                {{ 'Billing Issue' }}
                                                            {% elif listing.category and listing.category == 'accessissue' %}  
                                                                {{ 'Access Issue' }}  
                                                            {% elif listing.category and listing.category == 'payrollissue' %}   
                                                                {{ 'Payroll Issue' }} 
                                                            {% endif %}    
                                                        </td>  

                                                        <td>{{ listing.description }}</td>                                                    
                                                        <td>{{ listing.organization__name | title }}</td>                                                    
                                                        <td>{{ listing.comments }}</td>                                                    
                                                        <td>{{ listing.raised_by.name | title }}</td>                                                    
                                                        <td>{{ listing.resolved_by.name | title }}</td>                                                    
                                                        <td>{{ listing.created_at|date:"M d, Y" }}</td>                                                    
                                                        <td>

                                                            {% if listing.status and listing.status == 'pen' %}
                                                                {{ 'Pending' }}
                                                            {% elif listing.status and listing.status == 'res' %}  
                                                                {{ 'Resolved' }}  
                                                            {% elif listing.status and listing.status == 'inv' %}   
                                                                {{ 'Invalid' }} 
                                                            {% elif listing.status and listing.status == 'pro' %}   
                                                                {{ 'Processing' }} 
                                                            {% endif %} 

                                                            {% comment %} <select onchange="changeStatus('{{listing.ticket_id}}',this.value);" id="ticket_status" name="ticket_status" class="multiselect multiselect-custom single-selection">
                                                                <option {% if listing.status == '' %}{{'selected'}}{% else %}{{''}}{% endif %} value="">Select Ticket Status</option>
                                                                <option {% if listing.status == 'pen' %}{{'selected'}}{% else %}{{''}}{% endif %} value="pen" >Pending</option>
                                                                <option {% if listing.status == 'res' %}{{'selected'}}{% else %}{{''}}{% endif %} value="res" >Resolved</option>
                                                                <option {% if listing.status == 'inv' %}{{'selected'}}{% else %}{{''}}{% endif %} value="inv" >Invalid</option>
                                                                <option {% if listing.status == 'pro' %}{{'selected'}}{% else %}{{''}}{% endif %} value="pro" >Processing</option>
                                                            </select> {% endcomment %}
                                                        </td>                                                                                                       
                                                    </tr>

                                                {% endfor %} 

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                              
                            </div>
                        </div>
                    </div>
                </div>
            </div>

{% endblock main_content %}

{% block js %}

<script type="text/javascript">
    function changeStatus(baseId,ticket_status){

        if(ticket_status != ''){
      
            var csrfmiddlewaretoken = "{{csrf_token}}";
            // Send the data using post
            $.ajax({
                type: "POST",
                url: "{% url 'support:ticketapi_auto_update' %}",
                headers: {
                    "Authorization": "Bearer "+localStorage.getItem('acc_token')
                },
                data: {"status" : ticket_status, "ticket_id":baseId, 'csrfmiddlewaretoken':csrfmiddlewaretoken },
                dataType : 'json',
                beforeSend:function(){
                    return confirm("Are you sure! Want to change the Status?");
                },
                success: function(result){
                    console.log(result);
                    {% comment %} var result = $.parseJSON(response); {% endcomment %}
                    
                    if((result.response).trim() == 'success' && result.msg == ''){
                        swal({   
                            title:"Success",
                            text: "Status has been changed successfully",  
                            type: "success",
                            confirmButtonColor: "#007bff",
                            confirmButtonText: "Ok",
                            closeOnConfirm: true  
                        },function() { 
                            location.reload();
                        });
                    }else if(result.msg != ''){
                        swal({ 
                            title: (result.title).trim(),
                            text: (result.msg).trim(), 
                            type: (result.type).trim(),
                            confirmButtonColor: "#007bff",
                            confirmButtonText: "Ok",
                            closeOnConfirm: true  
                        },function() { 
                            location.reload();
                        });
                    }else{
                        swal({   
                            title:"Error",
                            text: "Something went wrong! Please try after some time.",  
                            type: "error",
                            confirmButtonColor: "#007bff",
                            confirmButtonText: "Ok",
                            closeOnConfirm: true  
                        },function() { 
                            location.reload();
                        });
                    }
                },
                error:function(xhr, status, err) {
                    console.log(xhr);
                    console.log(status);
                    alert('Error - '+err);
                }
            });
        }else{
            swal({   
                title:"Required",
                text: "Please select status",  
                type: "info",
                confirmButtonColor: "#007bff",
                confirmButtonText: "Ok",
                closeOnConfirm: true  
            },function() { 
                location.reload();
            });
        }
    }
</script>

{% endblock js %}

support/templates/ticket.html
{% extends 'payroll/base/base.html' %}
{% load static %}

{% block main_content%}
    
    {% for ticket in data  %}
        {{ticket}} <br> <br>
    {% endfor %}
        
    <br>
        <div class="container">
            <hr>
        
            <div class="form-group">
            <label>title</label>
            <input type="text" name="title" id="title" placeholder="title" size="15" required /><br>
            </div>
            <br>

            <div class="form-group">
            <label for="category">category</label>
            <select id="category" name="category" class="multiselect multiselect-custom single-selection">
                <option value="">Select Category</option>
                <option value="billingissue" >Billing Issue</option>
                <option value="accessissue" >Access Issue</option>
                <option value="payrollissue" >Payroll Issue</option>
            </select>
            </div>
            <br>
        <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" name="description" id="description" rows="3"></textarea>
        </div>
        <br>
    
        <button onclick="submittitle()">Click me</button>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
{%endblock%}

{% block js %}
<script type="text/javascript">
            
function submittitle(){
    $.ajax({
        type: "POST",
        url: "{% url 'support:ticketapi_create' %}",
        headers: {
            "Authorization": "Bearer "+localStorage.getItem('acc_token')
        },
        data: {"title":document.getElementById('title').value, "category":document.getElementById('category').value , "description": document.getElementById('description').value},
        success: function (response) {
            console.log("created", response)
        },
        error:function(xhr, status, e) {
            alert('Error',e);
        }
    });
}

</script>

{%endblock%}