src/HRMSProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from .docs.generators import OpenAPISchemaGenerator
from .docs.swagger_intro import DESCRIPTION

from .db_setup import DBCreation, CentralCompanyCreationAPIView, CreateCompany

app_urls = [
    path("admin/", admin.site.urls),
    path('api/roles/', include("roles.urls")),
    path("api/user/", include("HRMSApp.urls")),
    path("api/company/", include("company_profile.urls")),
    path("api/directory/", include("directory.urls")),
    path("api/choices/", include("choices.urls")),
    path("api/reports/", include("reports.urls")),
    path("api/pss_calendar/", include("pss_calendar.urls")),
    path("api/leave/", include("leave.urls")),
    path("api/attendance/", include("attendance.urls")),
    path("api/performance_management/", include("performance_management.urls")),
    path("api/investment_declaration/", include("investment_declaration.urls")),
    path("api/payroll/", include("payroll.api_urls")),
    path("payroll/", include("payroll.urls")),    
    path('support/', include(("support.urls", "support"), namespace='support')),
    path('billing/', include(("billing.urls", "billing"), namespace='billing')),
    path('central/db_setup/', CreateCompany.as_view()),
    path('central/company_setup/', CentralCompanyCreationAPIView.as_view()),
    path('api/aiml/', include("aiml_app.urls")),
    path('api/alerts/', include("alerts.urls")),
    path('api/onboarding/', include("onboarding.urls")),
]


schema_view = get_schema_view(
    openapi.Info(
        title="HRMS Software API",
        default_version="v1",
        description=DESCRIPTION,
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@pss.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    generator_class=OpenAPISchemaGenerator,
    patterns=app_urls,
)

external_urls = [
    # re_path(
    #     r"^swagger(?P<format>\.json|\.yaml)$",
    #     schema_view.without_ui(cache_timeout=0),
    #     name="schema-json",
    # ),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # re_path(
    #     r"^docs/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    # ),
    # OpenAPI schema
    # path(
    #     "docs/",
    #     schema_view.with_ui("redoc", cache_timeout=0),
    #     name="openapi-schema",
    # ),
]

urlpatterns = external_urls + app_urls
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/billing/urls.py
from django.urls import path

from .views import BillingAPIView

app_name = 'billing'

urlpatterns = [
    path('view/', BillingAPIView.as_view(), name='view'),
    path('auto/create/', BillingAPIView.as_view(), name='auto_create'),
    path('auto/update/', BillingAPIView.as_view(), name='auto_update'),
]

src/payroll/urls.py
from django.urls import path

from payroll.web_views import (    
    activeEmployees,
    # createPayRun,
    departments,
    designations,
    employeeBankDetail,
    employeeLopDetail,
    employeePayslips,
    employeePayslipsDetail,
    employeeSalary,
    employeeSalaryEdit,
    esiComplianceReport,
    importOvertimeEmployees,
    # By Uday Shankar Start
    manageEmployees,
    importLeaveEmployees,
    profileViewEmployees, 
    profileEditEmployees, 
    profileAddEmployees, 
    importDataEmployees,
    repAllMonthTDSReport,
    repGratutyReports,
    repHoldSalary,
    savingAllEmpForms,
    savingDeclarationSetup, 
    taxDetailsEdit, 
    organizationSetupEdit, 
    repPayrollOverview,    
    repEmpReports,
    repPtSummary,
    repEpfSummary,
    repEsiSummary,
    repPtSlab,
    leaveReportsView,
    # By Uday Shankar End
    epfDetails,
    epfDetailsEdit,
    esiDetails,
    esiDetailsEdit,
    organizationView,
    payrollMaster,
    paySchedule,
    payScheduleEdit,
    profTaxes,
    profTaxesEdit,
    runPayroll,
    salComponent,
    salComponentAdd,
    salComponentEdit,
    singleSalComponent,
    taxDetails,
    employeeBankDetailEdit,
    rollbackPayroll,
    DashboardView,
    repAuditReport,
    repMissingInfoReport,
    repSalaryInfoReport,    
    repVarianceReport,
    repLogReport,
    savingDeclarationForms,
    savingUserSubmittedForms,
    savingApproveEmpForms,
    reimbursement_employee,
    complianceGovtReport,
    importVariablePayEmployees
)



urlpatterns = [
    #######################################
    # Web urls
    #######################################
    path(
        "epf-details/",
        epfDetails,
        name="epf_details",
    ),
    path(
        "epf-details-edit/<int:epfId>",
        epfDetailsEdit,
        name="epf_details_edit",
    ),
    path(
        "esi-details/",
        esiDetails,
        name="esi_details",
    ),
    path(
        "esi-details-edit/<int:esiId>", 
         esiDetailsEdit, 
         name="esi_details_edit"
         ),
    path(
        "professional-taxes/",
        profTaxes,
        name="professional_taxes",
    ),
    path(
        "professional-tax-edit/<int:ptId>",
        profTaxesEdit,
        name="professional_taxes_edit",
    ),
    path(
        "salary-component/",
        salComponent,
        name="salary_component",
    ),
    path(
        "salary-component-edit/<int:sal_comp_id>",
        salComponentEdit,
        name="salary_component_edit",
    ),
    path(
        "salary-component-view/<int:sal_comp_id>",
        singleSalComponent,
        name="salary_component_view",
    ),
    path(
        "salary-component-add/",
        salComponentAdd,
        name="salary_component_add",
    ),
    path(
        "active-employees/",
        activeEmployees,
        name="active_employees_view",
    ),
    path(
        "rollback-payroll/",
        rollbackPayroll,
        name="rollback_payroll",
    ),
    path(
        "compliance-report/",
        complianceGovtReport,
        name="compliance_govt_report",
    ),
    # By Uday Shankar Start
    path(
        "manage-employees/",
        manageEmployees,
        name="manage_employees_view",
    ),
    path(
        "import-leave-employees/",
        importLeaveEmployees,
        name="import_leave_employees_view",
    ),
    path(
        "import-overtime-employees/",
        importOvertimeEmployees,
        name="import_overtime_employees_view",
    ),
     path(
        "import-variable-pay-employees/",
        importVariablePayEmployees,
        name="import_variable_pay_employee_view",
    ),
    path(
        "profile-edit-employees/<int:emp_id>",
        profileEditEmployees,
        name="profile_edit_employees",
    ),
    path(
        "profile-view-employees/<int:emp_id>",
        profileViewEmployees,
        name="profile_view_employees",
    ),
    path(
        "profile-add-employees/",
        profileAddEmployees,
        name="profile_add_employee",
    ),
    path(
        "import-data-employees/",
        importDataEmployees,
        name="import_data_employee",
    ),
    path(
        "organization/tax-details-edit/",
        taxDetailsEdit,
        name="tax_details_edit",
    ),
    path(
        "organization/organization-setup-edit/",
        organizationSetupEdit,
        name="organization_setup_edit",
    ),
    path(
        "reports/payroll-overview/",
        repPayrollOverview,
        name="rep_payroll_overview",
    ),
    path(
        "reports/epf-summary/",
        repEpfSummary,
        name="rep_epf_summary",
    ),
    path(
        "reports/esi-summary/",
        repEsiSummary,
        name="rep_esi_summary",
    ),
    path(
        "reports/emp-reports/",
        repEmpReports,
        name="rep_emp_reports",
    ),
    path(
        "reports/pt-summary/",
        repPtSummary,
        name="rep_pt_summary",
    ),   
  
    path(
        "reports/pt-slab/",
        repPtSlab,
        name="rep_pt_slab",
    ),

    path(
        "reports/all_monthly_tds/",
        repAllMonthTDSReport,
        name="repAllMonthTDSReport",
    ),
    
    path(
        "reports/hold_salary/",
        repHoldSalary,
        name="repHoldSalary",
    ),        

    path(
        "reports/leave/reports/",
        leaveReportsView,
        name="leave_report",
    ),

    path(
        "reports/gratuty/",
        repGratutyReports,
        name="gratuty_report",
    ),    
    
    path(
        "saving/declaration/forms/",
        savingDeclarationForms,
        name="saving_declaration_forms",
    ),
    path(
        "saving/declaration/setup/",
        savingDeclarationSetup,
        name="saving_declaration_setup",
    ),    
    
    path(
        "saving/declaration/user-submitted/<int:id>",
        savingUserSubmittedForms,
        name="user_submitted_forms",
    ),
    
    path(
        "saving/declaration/approve-employee/forms/",
        savingApproveEmpForms,
        name="approve_employee_form",
    ),
    path(
        "saving/declaration/submitted-employee/forms/",
        savingAllEmpForms,
        name="saving_all_employee_forms",
    ),
    path(
        "reports/audit-report",
        repAuditReport,
        name="audit_report"
    ),
    path(
        "reports/missing-info-report",
        repMissingInfoReport,
        name="missing_info_report"
    ),
    path(
        "reports/salary-info-report",
        repSalaryInfoReport,
        name="salary_info_report"
    ),
    # path(
    #     "reports/monthly-tds-report",
    #     repMonthlyTDSReport,
    #     name="monthly_tds_report"
    # ),    
    # path(
    #     "reports/salary-breakup-report",
    #     repSalaryBreakupReport,
    #     name="salary_breakup_report"
    # ),  

    path(
        "reports/esi-compliance-report",
        esiComplianceReport,
        name="esi_compliance_report"
    ),     
    path(
        "reports/variance-report",
        repVarianceReport,
        name="variance_report"
    ), 
    path(
        "reports/log-report",
        repLogReport,
        name="log_report"
    ),        
    path(
        "employee-salary/<int:id>",
        employeeSalary,
        name="employee_salary",
    ),
    path(
        "employee-salary-edit/<int:id>",
        employeeSalaryEdit,
        name="employee_salary_edit",
    ),
    path(
        "employee-bank-details/<int:id>",
        employeeBankDetail,
        name="employee_bank_details",
    ),
    path(
        "employee-bank-details-edit/<int:id>",
        employeeBankDetailEdit,
        name="employee_bank_details_edit",
    ),
    path(
        "employee-lop-details/<int:id>", employeeLopDetail, name="employee_lop_details"
    ),
    path("employee-payslips/<int:emp_id>", employeePayslips, name="employee_payslips"),
    path(
        "employee-payslip-view/",
        employeePayslipsDetail,
        name="employee_payslips_details",
    ),
    path("run-payroll/", runPayroll, name="run_payroll"),
    # path("create-pay-run/", createPayRun, name="create_pay_run"),
    path("payroll-master/", payrollMaster, name="payroll_master"),
    
    path("organization/", organizationView, name="organization_view"),
    path("dashboard/<int:company_id>/<str:token>", DashboardView, name="Dashboard_view"),
    
    path("reimbursement/", reimbursement_employee, name="reimbursement"),


    path("organization/pay-schedule/", paySchedule, name="pay_schedule"),
    path("organization/pay-schedule-edit/", payScheduleEdit, name="pay_schedule_edit"),
    
    path("organization/tax-details/", taxDetails, name="tax_details"),
    path("organization/departments/", departments, name="departments"),
    path("organization/designations/", designations, name="designations"),
    
]

support/urls.py
from django.urls import path

from .views import TicketApiView, CentralTicketUpdateAPIView

urlpatterns = [
    path('ticketapi/', TicketApiView.as_view(), name='ticketapi'),
    path('ticketapi/listing-tickets/', TicketApiView.as_view(), name='listing_ticketapi'),
    path('ticketapi/create/', TicketApiView.as_view(), name='ticketapi_create'),
    path('ticketapi/auto/update/', CentralTicketUpdateAPIView.as_view(), name='ticketapi_auto_update'),
]

src/payroll/templates/payroll/base/css.html
{% load static %}

    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/animate-css/vivify.min.css' %}">

    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/sweetalert/sweetalert.css' %}">


    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/qxbox/{% static 'assets/css/site.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/css/common.css' %}">


    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/parsleyjs/css/parsley.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/multi-select/css/multi-select.css' %}">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/jquery-steps/jquery.steps.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/dropify/css/dropify.min.css' %}">
    <link rel="stylesheet" href="/qxbox/{% static 'assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}">

    <style>        
        .NofEntriesShowSel {
            width: 70px;
        }
        td.details-control {
            background: url('/qxbox/{% static "assets/images/details_open.png" %}') no-repeat center center;
        cursor: pointer;
        }
        tr.shown td.details-control {
            background: url('/qxbox/{% static "assets/images/details_open.png" %}') no-repeat center center;
        }

        .parsley-errors {
            color: rgb(225, 88, 88);
            font-size: 0.9em;
            margin-top: 3px;
        }
        .navbar-brand .logo{
            /* height:28px !important; */
            width: 160px !important;
        }
    </style>


<style>
    #menuBtn:active {
        border: 2px solid #30239f;
    }
    #menuBtn:visited {
        border: 2px solid #30239f;
    }

    #menuBtn:focus {
        border: 2px solid #30239f;
        outline: 1px dotted !important;
    }
</style>

<style>




#AjaxCallBtn{
    display:block;
    margin:20px auto;
    padding:10px 30px;
    background-color:#eee;
    border:solid #ccc 1px;
    cursor: pointer;
}
#AjaxCallOverlay{   
    position: fixed;
    top: 0;
    z-index: 100;
    width: 100%;
    height:100%;
    display: none;
    background: rgba(0,0,0,0.6);
}
.AjaxCallSpinner {
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;  
}
.AjaxSpinner {
    width: 40px;
    height: 40px;
    border: 4px #ddd solid;
    border-top: 4px #2e93e6 solid;
    border-radius: 50%;
    animation: sp-anime 0.8s infinite linear;
}
@keyframes sp-anime {
    100% { 
        transform: rotate(360deg); 
    }
}
.is-hide{
    display:none;
}



</style>

<style>
	#infoIconAboutRunPayrollBtn {
		position: absolute;
		right: 220px;
		cursor: pointer;
	}

	.RunPayrollInfoBtn:hover {
	  cursor: pointer;
	}

	.RunPayrollInfoBtn:hover+.TooltipCompliancePopup{
	  display: block;
	}

    .TooltipCompliancePopup {
		display: none;
        width: 200px;
        box-shadow: 0px 0px 3px #aaa;
        background-color: #fff;
        right: 0%;
	}

</style>

src/payroll/templates/payroll/base/emp-block-header.html
<div class="header w-100">
    <ul class="nav nav-tabs2 text-center">
        <li class="nav-item px-0" style="width: 20%; margin-left: 20px; margin-right: 20px;">
            <a class="nav-link show pt-3 pb-3 {% if t1 %}active{% endif %}"  id="EPF_listtypes" href="/qxbox{% url 'active_employees_view' %}">Active Employees</a>
        </li>
         <li class="nav-item px-0 manage_emp" style="width: 20%; margin-left: 20px; margin-right: 20px;">
        <!-- <a class="nav-link pt-3 pb-3 {% if t2 %}active{% endif %}" id="EPF_listtypes" href="/qxbox{% url 'manage_employees_view' %}">Manage Employee</a>
        </li>
        <li class="nav-item px-0 imp_exp_leaves" style="width: 20%; margin-left: 20px; margin-right: 20px;">
            <a class="nav-link pt-3 pb-3 {% if t3 %}active{% endif %}" id="EPF_listtypes" href="/qxbox{% url 'import_leave_employees_view' %}">Import Leave/LOP</a>
        </li>
        <li class="nav-item px-0 imp_exp_leaves" style="width: 20%; margin-left: 20px; margin-right: 20px;">
            <a class="nav-link pt-3 pb-3 {% if t4 %}active{% endif %}" id="EPF_listtypes" href="/qxbox{% url 'import_overtime_employees_view' %}">Import Overtime</a>
        </li>
        <li class="nav-item px-0 imp_exp_leaves" style="width: 20%; margin-left: 20px; margin-right: 20px;">
            <a class="nav-link pt-3 pb-3 {% if t5 %}active{% endif %}" id="EPF_listtypes" href="/qxbox{% url 'import_variable_pay_employee_view' %}">Import Variable Pay</a>
        </li> -->
    </ul>
</div>

src/payroll/templates/payroll/base/js.html
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>


<!-- Javascript -->
<script src="/qxbox{% static 'assets/js/ajax.js' %}"></script>
<script src="/qxbox{% static 'assets/bundles/libscripts.bundle.js' %}"></script>
<script src="/qxbox{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script>

<script src="/qxbox{% static 'assets/bundles/datatablescripts.bundle.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/jquery-datatable/buttons/dataTables.buttons.min.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/jquery-datatable/buttons/buttons.colVis.min.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/jquery-datatable/buttons/buttons.html5.min.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/sweetalert/sweetalert.min.js' %}"></script><!-- SweetAlert Plugin Js -->
<script src="/qxbox{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>
<script src="/qxbox{% static 'assets/js/pages/ui/dialogs.js' %}"></script>
<script src="/qxbox{% static 'assets/js/pages/tables/jquery-datatable.js' %}"></script>

<script src="/qxbox{% static 'assets/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js' %}"></script><!-- Bootstrap Colorpicker Js -->
<script src="/qxbox{% static 'assets/vendor/jquery-inputmask/jquery.inputmask.bundle.js' %}"></script><!-- Input Mask Plugin Js -->
<script src="/qxbox{% static 'assets/vendor/jquery.maskedinput/jquery.maskedinput.min.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/multi-select/js/jquery.multi-select.js' %}"></script><!-- Multi Select Plugin Js -->
<script src="/qxbox{% static 'assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js' %}"></script>
<script src="/qxbox{% static 'assets/js/pages/forms/advanced-form-elements.js' %}"></script>

<script src="/qxbox{% static 'assets/vendor/parsleyjs/js/parsley.min.js' %}"></script>

<script src="/qxbox{% static 'assets/vendor/jquery-validation/jquery.validate.js' %}"></script><!-- Jquery Validation Plugin Css -->
<script src="/qxbox{% static 'assets/vendor/jquery-steps/jquery.steps.js' %}"></script><!-- JQuery Steps Plugin Js -->
<script src="/qxbox{% static 'assets/js/pages/forms/form-wizard.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/dropify/js/dropify.min.js' %}"></script>
<script src="/qxbox{% static 'assets/js/pages/forms/dropify.js' %}"></script>
<script src="/qxbox{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script> <!--Employee payroll analytics link -->


<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.13.7/api/sum().js"></script>

src/payroll/templates/payroll/base/left_sidebar.html
<style>
    .break-word {
        word-wrap: break-word;
}
</style>

<div id="left-sidebar" class="sidebar theme1">
    <div class="sidebar-scroll">
        <div class="user-account">
            <div class="user_div">             
            </div>
            <div class="dropdown">
                <a href="javascript:void(0);" class="dropdown-toggle user-name" data-toggle="dropdown" style="font-size: 16px;">
                    Welcome
                </a>
                <ul class="dropdown-menu dropdown-menu-right account vivify flipInY">
                    <strong class="comp-name break-word w-100"></strong>
                    <li><a href="#"  onclick="log_out()"><i class="icon-power"></i>Logout</a></li>
                </ul>
                <div class="user_div pb-1 pt-2" id="user_img_div">                    
                </div>
            </div>
        </div>
        <nav id="left-sidebar-nav" class="sidebar-nav">
            <ul id="main-menu" class="metismenu">
                <li><a class="dashLink" href=""><i class="icon-speedometer"></i><span>Dashboard</span></a></li>
                <li><a href="/qxbox{% url 'payroll_master' %}">
                    <i class="fa fa-inr" aria-hidden="true"></i>
                    <span>Payroll Master</span></a>
                </li>
                
                <!-- <li id="orgSetupNavItem"><a href="/qxbox{% url 'organization_view' %}"><i class="icon-grid"></i><span>Organization Setup</span></a></li> -->
                <li id="orgSetupNavItem"><a href="/qxbox{% url 'organization_view' %}"><i class="icon-grid"></i><span>Payslip Setup</span></a></li>


                <li id="payrollCompNavItem"><a href="/qxbox{% url 'epf_details' %}">
                    <i class="fa fa-list" aria-hidden="true"></i>
                    <span>Payroll Component</a>
                </li>
                <li id="employeeNavItem"><a href="/qxbox{% url 'active_employees_view' %}"><i class="icon-users"></i><span>Employees</span></a></li>  
                                  
                <li id="SavingDeclartion"><a href="/qxbox{% url 'saving_all_employee_forms' %}">                    
                    <i class="fa fa-money" aria-hidden="true"></i>
                    <span>Saving Declarations</span></a>
                </li>    
                
                <li><a href="/qxbox{% url 'reimbursement' %}" class="has-arrow">                   
                    <i class="fa fa-table" aria-hidden="true"></i>
                    <span>Reimbursement</span></a>
                </li>
                
                <li id="MainMenu">
                    <a href="#demo6" class="list-gre" data-toggle="collapse" data-parent="#MainMenu">                  
                        <i class="fa fa-bar-chart" aria-hidden="true"></i>
                        <span>Reports</span><i class="fa fa-caret-down"></i>
                    </a>
                    <div class="collapse pl-3" id="demo6">
                        <a href="/qxbox{% url 'rep_payroll_overview' %}" class="has-arrow">
                            <i class="fa fa-suitcase" aria-hidden="true"></i>
                            <span>Statutory Reports</span>
                        </a>
                        <a href="/qxbox{% url 'repAllMonthTDSReport' %}" class="has-arrow"><i class="fa fa-sort-numeric-asc" aria-hidden="true"></i><span>Monthly TDS Reports</span></a>
                        <a href="/qxbox{% url 'gratuty_report' %}" class="has-arrow"><i class="fa fa-sort-numeric-asc" aria-hidden="true"></i><span>Gratuty Reports</span></a>
                      
                        <a href="/qxbox{% url 'missing_info_report' %}" class="has-arrow"><i class="fa fa-user-secret" aria-hidden="true"></i><span>Missing Info Reports</span></a>
                        <a href="/qxbox{% url 'salary_info_report' %}" class="has-arrow"><i class="fa fa-pie-chart" aria-hidden="true"></i><span>Salary Info Reports</span></a>
                        
                        <a href="/qxbox{% url 'variance_report' %}" class="has-arrow"><i class="fa fa-tasks" aria-hidden="true"></i><span>Variance Reports</span></a>
                        <a href="/qxbox{% url 'audit_report' %}" class="has-arrow"><i class="fa fa-list-ol" aria-hidden="true"></i><span>Audit Reports</span></a> 
                      
                        <a href="/qxbox{% url 'leave_report' %}" class="has-arrow"><i class="fa fa-plane" aria-hidden="true"></i><span>Leave Report</span></a> 
                        <a href="/qxbox{% url 'repHoldSalary' %}" class="has-arrow"><i class="fa fa-plane" aria-hidden="true"></i><span>Hold Salary Report</span></a> 
                    </div>
                </li>
              

                <li><a href="/qxbox{% url 'compliance_govt_report' %}" class="has-arrow"><i class="icon-calculator"></i><span>EPF Compliance Report</span></a></li>
                <li><a href="/qxbox{% url 'esi_compliance_report' %}" class="has-arrow"><i class="icon-calculator"></i><span>ESI Compliance Report</span></a></li>
                
                <!-- <li><a href="{% url 'billing:view' %}" class="has-arrow"><i class="icon-calculator"></i><span>Billing</span></a></li>
                <li><a href="{% url 'support:ticketapi' %}" class="has-arrow"><i class="icon-calculator"></i><span>Support</span></a></li>
                           
                 -->
            </ul>
        </nav>
    </div>
</div>